#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "${SCRIPT_DIR}/../common.sh"

usage() {
cat <<EOF

This script generates keys for Verified Boot in the KEYS_DIRECTORY. Please refer
to the Dasharo documentation for more information:
https://docs.dasharo.com/common-coreboot-docs/vboot_signing/

Usage: $0 KEYS_DIRECTORY

  Arguments:
    KEYS_DIRECTORY     path to directory where generated keys should be located

Example usage:
    $0 keys
EOF
  exit 0
}

KEYS_DIRECTORY="$(readlink -f $1)"
source "${SCRIPT_DIR}/env"

[ -z "${KEYS_DIRECTORY}" ] && echo "KEYS_DIRECTORY not given" && usage

docker run --rm -v ${PWD}:${PWD} -w ${PWD} ${CONTAINER} \
  /vboot/scripts/keygeneration/make_arv_root.sh "${KEYS_DIRECTORY}/arv_root"

errorCheck "Failed to generate vboot ARV root key"

docker run --rm -v ${PWD}:${PWD} -w ${PWD} ${CONTAINER} \
  /vboot/scripts/keygeneration/create_new_keys.sh \
    --8k-root --8k-recovery \
    --arv-root-path "${KEYS_DIRECTORY}/arv_root" \
    --output "${KEYS_DIRECTORY}/vboot"

errorCheck "Failed to generate keys"

echo "The Verified Boot keys were generated into following directory: ${KEYS_DIRECTORY}"
