#!/usr/bin/env sh

HWDB_FILE="/etc/udev/hwdb.d/60-keyboard.hwdb"
PRODUCT_NAME=$(dmidecode -s baseboard-product-name)
MANUFACTURER="$(dmidecode -s baseboard-manufacturer)"

echo "Found $MANUFACTURER $PRODUCT_NAME"

case "$PRODUCT_NAME" in
  V5xTNC_TND_TNE|V54x_6x_TU|NV4xPZ)
    :
    ;;
  *)
    echo "Microphone switch only supported on V54x, V56x and NV4xPZ laptops"
    exit 1
    ;;
esac

echo "evdev:atkbd:dmi:bvn*:bvr*:svn${MANUFACTURER}:pn${PRODUCT_NAME}:*" > "$HWDB_FILE"
echo "        KEYBOARD_KEY_81=f20" >> "$HWDB_FILE"

systemd-hwdb update
udevadm trigger

echo "The $HWDB_FILE has been created successfully."
echo "The touchpad FN+4 switch should be fixed after reboot."
echo "The system will reboot in 10 seconds. Press Ctrl+C to abort."

sleep 10
systemctl reboot
